server:
  port: 8080
spring:
  datasource:
    task:
      jdbcUrl: jdbc:postgresql://localhost:5432/tasks_repository
      username: badmin
      password: badminpass
      driver-class-name: org.postgresql.Driver